### ISSUE TITLE
open cv error -Ill-conditioned matrix 

### ISSUE THREAD

**Issue by charika1987** [DavidTorresOcana/image_pipeline#1]
I did the intrinsic calibration for my 100 HFOV gmsl cameras using yourimage_pipeline. However, if I use images where the checkerboard positioned close to the corners of the image, it gives me this open cv error: (-3) CALIB_CHECK_COND — Ill-conditioned matrix for input array 0 in function CalibrateExtrinsics. Therefore I had to remove all the images with corner coverage. But the results were acceptable. I checked with the camera_ckecker reprojection values. If I remove the CALIB_CHECK_COND during the calibration then I am not getting the above error but the intrinsic values are totally erroneous. I need to use images with corner coverage to improve the calibration. Is there any way I can do this? please be kind enough to share with me if you have any information in this regard. I have attached the images which cause the error. The 48 corners of my checkerboard can
![frame-3560-time-1539059716969827190](https://user-images.githubusercontent.com/45617480/49631161-15c94700-fa45-11e8-8967-b60464a4f395.png)
![frame-4220-time-1539059738976063430](https://user-images.githubusercontent.com/45617480/49631167-19f56480-fa45-11e8-8c47-3ffffaade255.png)

 be detected in these samples but still, it gives an error during optimization. I used the same images with Matlab fisheye calibration and it is causing no errors and giving very good parameters, However, the Matlab fish eye model is different from what we have in here.

**Comment by DavidTorresOcana** [comment]
Hello

Thank you for raising this issue.
According to the experiments with my camera, removing the flag CALIB_CHECK_COND does produce a good calibration without this error, even when positioning the chessboard close to the corners. 
A similar thread  [here](https://github.com/opencv/opencv/issues/7008)
This should be solve in the next commit.

It is very estrange that the calibration gives bad results without CALIB_CHECK_COND. I could not replicate this error. I would suggest to perform the calibration with as few samples as possible covering all the regions, since you would be making optimisation easier. 

For your camera: have you tried calibrate with the normal camera_calibration (uses pinhole model) ? Fisheye model normally applies when FOVs are really high.

**Comment by charika1987** [comment]
Hi,
if  I use the pinhole model with 5 distortion coefficients the undistortion fails in the edges. Even though my camera angle<180 still the lens is very small. so it is close to a fisheye I guess. Even the fish eye model calibration looks much better close to the corners. however, if I remove the condition check it gives an erroneous result. maybe this is related to my camera not being a real fisheye. if I enable the condition I have to manually select the images process an, therefore, cannot be done automatically.

**Comment by DavidTorresOcana** [comment]
Hi
This is very estrange. I have only 2 ideas:
* Try to make the calibration as fast as possible: When getting many samples, optimisation gets harder hence may not converge and fail.
* You said that enabling the condition does work but you need to select images manually: What kind of images/cases you need to remove? If they are really distinct cases, it may be possible to improve this tool to eliminate those cases automatically...

Have you tried the new commit?

Regards

**Comment by charika1987** [comment]
Hi,
I tried your new commit. the same issue is there. I tried with 5,8,10,15,20, 30 samples still the same error occurs if the corner covering samples are used. I am removing all the images where checkerboard is positioned close to corners and edges. Roughly when all the checkerboard corners are at least  300 pixels away from the edges the pipeline works. I can add that constraint to the pipeline. But I hope if I could use all the corner covering images it may improve the accuracy of the parameters at the edges. so I can use balance =1 in undistortion and use the entire image pixels in later processing without discarding any data. because the current calibration does not use any corner data and just extrapolate towards the corners.

**Comment by charika1987** [comment]
Hi There I also have another question. What does the linearity error measure? it seems to be a measure of the straightness of the lines. hope I am understanding this corectly

**Comment by DavidTorresOcana** [comment]
Hello

What do you mean with pinhole model the calibration fails on the edges?
With fisheye model, how is the calibration without corners coverage?
Please share the results of of those rectifications (mainly pinhole model result with corner coverage).
I do not know what linearity error is

Regards

**Comment by charika1987** [comment]
![1](https://user-images.githubusercontent.com/45617480/49839882-19721a80-fe05-11e8-8637-5398d87c1c4a.png)
![untitled](https://user-images.githubusercontent.com/45617480/49839887-20992880-fe05-11e8-976c-0bdbd37a3757.jpg)
 the first image from pinhole model 5 distortion coefficients with alpha=1
the second image is from fisheye model with balance 1

**Comment by DavidTorresOcana** [comment]
Hello

From my point of view both calibrations are equally good. I would stay with
pinhole.
As with any calibration of high fov cameras you won't be able to keep the
original fov but you can keep the original resolution with a good
interpolation method. You need to select alpha to keep the good portion of
the image .

Regards
