### ISSUE TITLE
Poor results

### ISSUE THREAD

**Issue by abylikhsanov** [DavidTorresOcana/image_pipeline#3]
Hi, 

I have used your package (only camera_calibration_fisheye without any other packages in your forked image_pipeline) as I do not have CUDA but after the calibration, I am getting the calibration value above 5, meaning that the calibration is poor. Are you getting good results? (less than 0.5)

**Comment by DavidTorresOcana** [comment]
Hello
Could you give more details? Where do you get that number from?
Are you using the interactive calibration tool?

The results I obtain are qualitatively good.
How do your rectified images look?

Regards
