### ISSUE TITLE
Running multiple fisheye rectify nodes

### ISSUE THREAD

**Issue by osholsonel20** [DavidTorresOcana/image_pipeline#6]
This is a great tool for us, however when trying to run on 4 different fisheye cameras it seems to take a huge performance hit.

I created the launch file and made 4 of these, one for each of our cameras. I notice huge latency issues on the cameras when doing so.

```console
 <node pkg="nodelet" type="nodelet" name="image_proc_fisheye" args="load image_proc_fisheye/RectifyNodelet camera_nodelet_manager" output="screen">
    <remap from="camera_info" to="/camera/color/camera_info" />
    <remap from="image_raw" to="/camera/color/image_raw" />
    <remap from="image_rect" to="/camera/color/image_rect" />
  </node>
```

**Comment by osholsonel20** [comment]
Looks like I needed multiple managers one for each image_proc_fisheye. Runs smooth, however my computer does start to get noisy... Is this meant to be ran on multiple cameras? Is there a specialized solution for that?

**Comment by DavidTorresOcana** [comment]
You can run as many rectification nodes (one for each camera) as needed with `image_proc_fisheye`, of course within the HW limits. 

This functionality (the one of `image_proc_fisheye`) is pending to be adopted in `noetic` with ros-perception/vision_opencv#358. That might be a more efficient manner to implement this functionality and you could rectify as explain [here](http://wiki.ros.org/image_proc?distro=noetic). You may want to wait for the PR to be merged or compile the PR branch yourself to check for performance.

Also, note there exist a [tool to calibrate fisheye cameras](http://wiki.ros.org/camera_calibration).
