### ISSUE TITLE
Fisheye cannot get calibrated

### ISSUE THREAD

**Issue by Fan-loewe** [DavidTorresOcana/image_pipeline#7]
Hello David,

Thank you for sharing the code! I used the code and followed this tutorial http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration

The only difference is that I used fisheye model (1) in the calibration GUI window.

Here are my result of calibration:
**** Calibrating ****
mono fisheye calibration...
D = [0.0, 0.0, 0.0, 0.0]
K = [152.78874536821954, 0.0, 239.5, 0.0, 152.78874536821954, 239.5, 0.0, 0.0, 1.0]
R = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P = [152.78874536821954, 0.0, 239.5, 0.0, 0.0, 152.78874536821954, 239.5, 0.0, 0.0, 0.0, 1.0, 0.0]

I feel strange because it gets the calibration result immediately. When I calibrated the pinhole camera, I need to wait half an hour for the results. Also, K and P are same if you don't count the last column. The parameters are too symmetric.

When I afterwards execute ROS_NAMESPACE=camera rosrun image_proc image_proc, I noticed the image of /camera/image_raw and that of /camera/image_rect_color almost same.

I am wondering, when I execute rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.108 image:=/camera/image_raw camera:=/camera, do I need to set some arguments specific for fisheye? Thanks a lot!

**Comment by DavidTorresOcana** [comment]
Hello

This repository is not maintained anymore.

If you need to calibrate a fisheye camera, I would recommend using Noetic distribution as its calibration tool already contains code in this repo and works properly. See [wiki](http://wiki.ros.org/camera_calibration)
 
For rectification, there is still no such officially released functionality as this PR ros-perception/vision_opencv#358 is still pending.
What you could do in the mean time is compile that PR's branch in your machine and use it.
I have tested it and it works as intended (as you are trying according to your comment).

Regards

**Comment by Fan-loewe** [comment]
Thanks a lot!
